name: "Build Server image"

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: ./docker/
          push: true
          tags: nehalko3087/nehalko:${{ github.sha }}  